# tasks/plugin_packages.yml
---
- name: zabbix_agent_plugin | Assert that zabbix_agent_plugin package state in valid value
  ansible.builtin.assert:
    that:
      - "zabbix_agent_package_state in ['present', 'latest']"
    msg: "'package_state' must be in 'present' or 'latest'."
    quiet: true
  when:
    - "zabbix_agent_install_plugin is defined"
    - "zabbix_agent_install_plugin | bool"

- name: zabbix_agent_plugin | Install zabbix-agent2 plugin packages
  ansible.builtin.package:
    name: "{{ zabbix_agent_plugin }}"
    state: "{{ zabbix_agent_package_state }}"
  when:
    - "zabbix_agent_install_plugin is defined"
    - "zabbix_agent_install_plugin | bool"
  notify: restart zabbix-agent

# Добавляем деплой кастомных плагинов (скрипты, обертки и т.д.)
- name: zabbix_agent_plugin | Deploy custom plugins and scripts
  ansible.builtin.include_tasks: deploy_plugins.yml
  when:
    - "zabbix_agent_install_plugin is defined"
    - "zabbix_agent_install_plugin | bool"