---
- name: Restart zabbix-agent
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['zabbix_agent_service'] }}"
    daemon_reload: "yes"
    state: "restarted"
  when:
    - "hostvars[inventory_hostname]['zabbix_agent'] is defined"
    - "hostvars[inventory_hostname]['zabbix_agent'] != ''"
    - "hostvars[inventory_hostname]['zabbix_agent'] |
       community.general.json_query(vars['zabbix_agent_restart']) is defined"
    - "hostvars[inventory_hostname]['zabbix_agent'] |
       community.general.json_query(vars['zabbix_agent_restart']) == 'true'"
  vars:
    zabbix_agent_restart: "[] | map(&restart || 'false', @) | [0]"
